apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: patroni-postgres
spec:
  source:
    type: Git
    git:
      uri: https://github.com/bcgov/patroni-postgres
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: patroni-postgres:latest
  triggers:
    - type: GitHub
      github:
        secret: your-github-webhook-secret
    - type: ConfigChange